package validator;

import java.util.Queue;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * This class has helper methods for parsing HTML tags.
 *
 * DO NOT EDIT THIS FILE!
 *
 * @author Josh Archer
 * @version 1.0
 */
public class RegexHelpers
{
    /**
     * Accepts an input string and queue. The method parses the string
     * for HTML elements found and adds them to the Queue. Any angle
     * brackets surrounding the tags are removed. For example, if "<aside>"
     * is found in the input string, then "aside" is added to the Queue.
     *
     * @param searchString the string to parse
     * @param tagsQueue the queue of HTML tags
     */
    public static void findTags(String searchString, Queue<String> tagsQueue)
    {
        Pattern pattern = Pattern.compile("<([^>\s]+)([^>]*)>");
        Matcher matches = pattern.matcher(searchString);
        while (matches.find())
        {
            tagsQueue.add(matches.group(1));
        }
    }
}
