package lists;

/**
 * Represents a singly-linked node for a linked list.
 *
 * DO NOT EDIT THIS FILE!
 *
 * @author Josh Archer
 * @version 1.0
 */
public class Node
{
    /*
        Note: This is breaking encapsulation, but we
        will keep our fields public to make things slightly
        easier for our exercises.
     */
    public int data;
    public Node next;

    /**
     * Constructors a node with a new element and
     * reference to the next node in the list.
     *
     * @param data the new data element
     * @param next the reference to the next node
     */
    public Node(int data, Node next)
    {
        this.data = data;
        this.next = next;
    }

    /**
     * Constructors a node with a new element.
     *
     * @param data the new data element
     */
    public Node(int data)
    {
        this.data = data;
    }
}
